name: prometheus-monitoring-rust-v2

services:
    prometheus:
      image: docker.io/prom/prometheus:v3.1.0 # Changed to 'latest' for simplicity or specify a desired version
      container_name: prom-rs-v2
      ports:
        - 9090:9090
      command: "--config.file=/etc/prometheus/prometheus.yaml --storage.tsdb.path=/prometheus" # Added storage path
      volumes:
        - ./prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
        - prometheus-rs:/prometheus
      restart: unless-stopped
      networks:
        - monitoring-network-rs

    grafana:
      image: docker.io/grafana/grafana-oss:11.5.1
      container_name: graf-rs-v2
      ports:
        - "3000:3000"
      volumes:
        - grafana-rs:/var/lib/grafana
      restart: unless-stopped
      networks:
        - monitoring-network-rs

    rust-monitoring:
      build:
        context: ./
        dockerfile: Dockerfile
      container_name: server-rs-v2
      ports:
        - "8000:8000"
      env_file:
        - .env
      networks:
        - monitoring-network-rs

volumes:
  prometheus-rs:
  grafana-rs:

networks:
  monitoring-network-rs:
    driver: bridge
