name: prometheus-monitoring4
services:
    prometheus:
      image: docker.io/prom/prometheus:v3.1.0 # Changed to 'latest' for simplicity or specify a desired version
      container_name: prometheus-v05
      ports:
        - 9090:9090
      command: "--config.file=/etc/prometheus/prometheus.yaml --storage.tsdb.path=/prometheus" # Added storage path
      volumes:
        - ./prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
        - prometheus:/prometheus
      restart: unless-stopped
      networks:
        - monitoring-network

    grafana:
      image: docker.io/grafana/grafana-oss:11.5.1
      container_name: grafana-v05
      ports:
        - "3000:3000"
      volumes:
        - grafana:/var/lib/grafana
      restart: unless-stopped
      networks:
        - monitoring-network

    rust-monitoring:
      build:
        context: ./
        dockerfile: Dockerfile
      container_name: rust-monitoring-server-v05
      ports:
        - "8000:8000"
      env_file:
      - .env
      networks:
        - monitoring-network

volumes:
  prometheus:
  grafana:

networks:
  monitoring-network:
    driver: bridge
